// Master catalog for generated sprite sheets.
// Each sheet is a strict 4x4 grid (16 items), generated as transparent line art.
// w/h are real-world defaults in centimeters (top-down footprint).

export const SHEETS = [
  {
    file: "g01-seating",
    items: [
      { id: "loveseat", label: "Loveseat", cat: "Seating", w: 150, h: 90, desc: "two-seat sofa" },
      { id: "sofa-l", label: "Corner sofa", cat: "Seating", w: 250, h: 200, desc: "L-shaped corner sofa" },
      { id: "chaise", label: "Chaise lounge", cat: "Seating", w: 170, h: 70, desc: "chaise lounge" },
      { id: "recliner", label: "Recliner", cat: "Seating", w: 90, h: 95, desc: "reclining armchair" },
      { id: "rocking-chair", label: "Rocking chair", cat: "Seating", w: 60, h: 90, desc: "rocking chair" },
      { id: "bench", label: "Bench", cat: "Seating", w: 140, h: 40, desc: "simple bench" },
      { id: "stool", label: "Stool", cat: "Seating", w: 35, h: 35, desc: "small round stool" },
      { id: "bar-stool", label: "Bar stool", cat: "Seating", w: 40, h: 40, desc: "bar stool with footring" },
      { id: "office-chair", label: "Office chair", cat: "Seating", w: 60, h: 60, desc: "office swivel chair with five wheels" },
      { id: "beanbag", label: "Bean bag", cat: "Seating", w: 90, h: 90, desc: "bean bag chair" },
      { id: "ottoman", label: "Ottoman", cat: "Seating", w: 60, h: 60, desc: "square ottoman" },
      { id: "pouf", label: "Pouf", cat: "Seating", w: 50, h: 50, desc: "round pouf" },
      { id: "egg-chair", label: "Egg chair", cat: "Seating", w: 90, h: 90, desc: "round egg chair" },
      { id: "folding-chair", label: "Folding chair", cat: "Seating", w: 45, h: 45, desc: "folding chair" },
      { id: "sofa-chaise", label: "Sofa w/ chaise", cat: "Seating", w: 250, h: 160, desc: "sofa with chaise section" },
      { id: "papasan", label: "Papasan chair", cat: "Seating", w: 100, h: 100, desc: "round papasan chair" },
    ],
  },
  {
    file: "g02-beds",
    items: [
      { id: "king-bed", label: "King bed", cat: "Beds", w: 190, h: 210, desc: "king size bed with two pillows" },
      { id: "bunk-bed", label: "Bunk bed", cat: "Beds", w: 95, h: 200, desc: "bunk bed with ladder" },
      { id: "crib", label: "Crib", cat: "Beds", w: 70, h: 130, desc: "baby crib with bars" },
      { id: "daybed", label: "Day bed", cat: "Beds", w: 95, h: 190, desc: "day bed" },
      { id: "futon", label: "Futon", cat: "Beds", w: 140, h: 190, desc: "futon mattress" },
      { id: "kids-bed", label: "Kids bed", cat: "Beds", w: 80, h: 160, desc: "children bed with toy" },
      { id: "round-bed", label: "Round bed", cat: "Beds", w: 220, h: 220, desc: "round bed" },
      { id: "sofa-bed", label: "Sofa bed", cat: "Beds", w: 160, h: 200, desc: "pulled-out sofa bed" },
      { id: "cot", label: "Cot", cat: "Beds", w: 65, h: 190, desc: "folding camping cot" },
      { id: "canopy-bed", label: "Canopy bed", cat: "Beds", w: 190, h: 215, desc: "four-poster bed with corner posts" },
      { id: "cradle", label: "Cradle", cat: "Beds", w: 55, h: 95, desc: "baby cradle" },
      { id: "toddler-bed", label: "Toddler bed", cat: "Beds", w: 70, h: 140, desc: "toddler bed" },
      { id: "platform-bed", label: "Platform bed", cat: "Beds", w: 200, h: 230, desc: "platform bed with side tables attached" },
      { id: "hospital-bed", label: "Hospital bed", cat: "Beds", w: 95, h: 210, desc: "hospital bed with rails" },
      { id: "murphy-bed", label: "Murphy bed", cat: "Beds", w: 160, h: 210, desc: "murphy wall bed folded out" },
      { id: "hammock-stand", label: "Hammock (stand)", cat: "Beds", w: 130, h: 300, desc: "hammock on a stand" },
    ],
  },
  {
    file: "g03-tables",
    items: [
      { id: "coffee-table", label: "Coffee table", cat: "Tables", w: 110, h: 60, desc: "rectangular coffee table" },
      { id: "coffee-table-round", label: "Round coffee table", cat: "Tables", w: 80, h: 80, desc: "round coffee table" },
      { id: "oval-table", label: "Oval table", cat: "Tables", w: 180, h: 110, desc: "oval dining table" },
      { id: "square-table-4", label: "Table + 4 chairs", cat: "Tables", w: 170, h: 170, desc: "square table with four chairs around it" },
      { id: "round-table-4", label: "Round table + 4", cat: "Tables", w: 180, h: 180, desc: "round table with four chairs around it" },
      { id: "table-8", label: "Table + 8 chairs", cat: "Tables", w: 280, h: 150, desc: "long dining table with eight chairs" },
      { id: "side-table", label: "Side table", cat: "Tables", w: 45, h: 45, desc: "small square side table" },
      { id: "console-table", label: "Console table", cat: "Tables", w: 120, h: 35, desc: "narrow console table" },
      { id: "bar-table", label: "Bar table", cat: "Tables", w: 60, h: 60, desc: "small round bar table" },
      { id: "l-desk", label: "L-shaped desk", cat: "Tables", w: 160, h: 160, desc: "L-shaped office desk" },
      { id: "standing-desk", label: "Standing desk", cat: "Tables", w: 140, h: 70, desc: "standing desk with monitor" },
      { id: "drafting-table", label: "Drafting table", cat: "Tables", w: 120, h: 80, desc: "tilted drafting table" },
      { id: "nightstand", label: "Nightstand", cat: "Tables", w: 45, h: 40, desc: "nightstand with lamp" },
      { id: "picnic-table", label: "Picnic table", cat: "Tables", w: 180, h: 150, desc: "picnic table with two benches" },
      { id: "poker-table", label: "Poker table", cat: "Tables", w: 130, h: 130, desc: "octagonal poker table" },
      { id: "vanity-table", label: "Vanity table", cat: "Tables", w: 110, h: 45, desc: "makeup vanity table with round mirror" },
    ],
  },
  {
    file: "g04-storage",
    items: [
      { id: "bookshelf", label: "Bookshelf", cat: "Storage", w: 90, h: 30, desc: "bookshelf with books seen from above" },
      { id: "bookcase-wide", label: "Wide bookcase", cat: "Storage", w: 160, h: 35, desc: "wide bookcase" },
      { id: "tv-stand", label: "TV stand", cat: "Storage", w: 160, h: 45, desc: "TV stand with flat television" },
      { id: "dresser", label: "Dresser", cat: "Storage", w: 120, h: 50, desc: "bedroom dresser" },
      { id: "drawers", label: "Chest of drawers", cat: "Storage", w: 80, h: 45, desc: "chest of drawers" },
      { id: "filing-cabinet", label: "Filing cabinet", cat: "Storage", w: 45, h: 60, desc: "filing cabinet" },
      { id: "shoe-rack", label: "Shoe rack", cat: "Storage", w: 80, h: 30, desc: "shoe rack with shoes" },
      { id: "coat-rack", label: "Coat stand", cat: "Storage", w: 50, h: 50, desc: "coat stand seen from above" },
      { id: "sideboard", label: "Sideboard", cat: "Storage", w: 160, h: 45, desc: "long sideboard" },
      { id: "china-cabinet", label: "China cabinet", cat: "Storage", w: 110, h: 45, desc: "china display cabinet" },
      { id: "safe", label: "Safe", cat: "Storage", w: 50, h: 50, desc: "floor safe with dial" },
      { id: "toy-chest", label: "Toy chest", cat: "Storage", w: 80, h: 45, desc: "toy chest" },
      { id: "laundry-basket", label: "Laundry basket", cat: "Storage", w: 45, h: 45, desc: "round laundry basket" },
      { id: "shelving-unit", label: "Shelving unit", cat: "Storage", w: 120, h: 40, desc: "open shelving unit" },
      { id: "display-cabinet", label: "Display cabinet", cat: "Storage", w: 100, h: 40, desc: "glass display cabinet" },
      { id: "wine-rack", label: "Wine rack", cat: "Storage", w: 60, h: 30, desc: "wine rack with bottles" },
    ],
  },
  {
    file: "g05-kitchen",
    items: [
      { id: "dishwasher", label: "Dishwasher", cat: "Kitchen", w: 60, h: 60, desc: "built-in dishwasher" },
      { id: "washing-machine", label: "Washing machine", cat: "Kitchen", w: 60, h: 60, desc: "washing machine with round door" },
      { id: "dryer", label: "Dryer", cat: "Kitchen", w: 60, h: 60, desc: "clothes dryer" },
      { id: "microwave", label: "Microwave", cat: "Kitchen", w: 50, h: 35, desc: "microwave oven" },
      { id: "double-oven", label: "Double oven", cat: "Kitchen", w: 60, h: 60, desc: "double wall oven" },
      { id: "chest-freezer", label: "Chest freezer", cat: "Kitchen", w: 110, h: 60, desc: "chest freezer" },
      { id: "mini-fridge", label: "Mini fridge", cat: "Kitchen", w: 50, h: 50, desc: "mini fridge" },
      { id: "kitchen-island", label: "Kitchen island", cat: "Kitchen", w: 180, h: 90, desc: "kitchen island with sink" },
      { id: "counter-l", label: "L-counter", cat: "Kitchen", w: 240, h: 240, desc: "L-shaped kitchen counter" },
      { id: "double-sink", label: "Double sink", cat: "Kitchen", w: 100, h: 55, desc: "double basin kitchen sink" },
      { id: "trash-bin", label: "Trash bin", cat: "Kitchen", w: 40, h: 40, desc: "round trash bin" },
      { id: "pantry", label: "Pantry cabinet", cat: "Kitchen", w: 90, h: 50, desc: "pantry cabinet" },
      { id: "breakfast-bar", label: "Breakfast bar", cat: "Kitchen", w: 180, h: 50, desc: "breakfast bar counter with two stools" },
      { id: "stove-6", label: "6-burner range", cat: "Kitchen", w: 90, h: 60, desc: "six burner professional range" },
      { id: "prep-table", label: "Prep table", cat: "Kitchen", w: 120, h: 60, desc: "stainless steel prep table" },
      { id: "kitchen-cart", label: "Kitchen cart", cat: "Kitchen", w: 70, h: 45, desc: "kitchen cart on wheels" },
    ],
  },
  {
    file: "g06-bathroom",
    items: [
      { id: "corner-tub", label: "Corner bathtub", cat: "Bathroom", w: 150, h: 150, desc: "quarter-circle corner bathtub" },
      { id: "oval-tub", label: "Freestanding tub", cat: "Bathroom", w: 170, h: 80, desc: "freestanding oval bathtub" },
      { id: "jacuzzi", label: "Jacuzzi", cat: "Bathroom", w: 200, h: 200, desc: "square jacuzzi with jets" },
      { id: "double-vanity", label: "Double vanity", cat: "Bathroom", w: 150, h: 55, desc: "double sink bathroom vanity" },
      { id: "single-vanity", label: "Single vanity", cat: "Bathroom", w: 75, h: 55, desc: "single sink bathroom vanity" },
      { id: "bidet", label: "Bidet", cat: "Bathroom", w: 40, h: 60, desc: "bidet" },
      { id: "urinal", label: "Urinal", cat: "Bathroom", w: 40, h: 35, desc: "wall urinal seen from above" },
      { id: "corner-shower", label: "Corner shower", cat: "Bathroom", w: 90, h: 90, desc: "quarter-circle corner shower" },
      { id: "walk-in-shower", label: "Walk-in shower", cat: "Bathroom", w: 140, h: 90, desc: "long walk-in shower with glass panel" },
      { id: "laundry-sink", label: "Utility sink", cat: "Bathroom", w: 55, h: 50, desc: "deep utility sink" },
      { id: "pedestal-sink", label: "Pedestal sink", cat: "Bathroom", w: 45, h: 45, desc: "round pedestal sink" },
      { id: "towel-cabinet", label: "Towel cabinet", cat: "Bathroom", w: 50, h: 35, desc: "towel storage cabinet" },
      { id: "clawfoot-tub", label: "Clawfoot tub", cat: "Bathroom", w: 160, h: 75, desc: "clawfoot bathtub" },
      { id: "double-shower", label: "Double shower", cat: "Bathroom", w: 160, h: 90, desc: "double wide shower" },
      { id: "changing-table", label: "Changing table", cat: "Bathroom", w: 90, h: 50, desc: "baby changing table" },
      { id: "accessible-toilet", label: "Accessible toilet", cat: "Bathroom", w: 50, h: 70, desc: "accessible toilet with grab rails" },
    ],
  },
  {
    file: "g07-fitness",
    items: [
      { id: "piano-grand", label: "Grand piano", cat: "Music & Fitness", w: 150, h: 160, desc: "grand piano" },
      { id: "piano-upright", label: "Upright piano", cat: "Music & Fitness", w: 150, h: 60, desc: "upright piano with bench" },
      { id: "treadmill", label: "Treadmill", cat: "Music & Fitness", w: 80, h: 180, desc: "treadmill" },
      { id: "exercise-bike", label: "Exercise bike", cat: "Music & Fitness", w: 60, h: 110, desc: "stationary exercise bike" },
      { id: "rowing-machine", label: "Rowing machine", cat: "Music & Fitness", w: 60, h: 210, desc: "rowing machine" },
      { id: "weight-bench", label: "Weight bench", cat: "Music & Fitness", w: 60, h: 130, desc: "weight bench with barbell" },
      { id: "squat-rack", label: "Squat rack", cat: "Music & Fitness", w: 120, h: 120, desc: "squat rack" },
      { id: "yoga-mat", label: "Yoga mat", cat: "Music & Fitness", w: 60, h: 180, desc: "rolled-out yoga mat" },
      { id: "elliptical", label: "Elliptical", cat: "Music & Fitness", w: 70, h: 160, desc: "elliptical trainer" },
      { id: "fireplace", label: "Fireplace", cat: "Music & Fitness", w: 120, h: 40, desc: "fireplace with mantel" },
      { id: "radiator", label: "Radiator", cat: "Music & Fitness", w: 100, h: 25, desc: "wall radiator" },
      { id: "massage-table", label: "Massage table", cat: "Music & Fitness", w: 70, h: 190, desc: "massage table with face hole" },
      { id: "dumbbell-rack", label: "Dumbbell rack", cat: "Music & Fitness", w: 110, h: 40, desc: "dumbbell rack" },
      { id: "gaming-desk", label: "Gaming setup", cat: "Music & Fitness", w: 160, h: 80, desc: "gaming desk with three monitors" },
      { id: "drum-kit", label: "Drum kit", cat: "Music & Fitness", w: 150, h: 130, desc: "drum kit" },
      { id: "keyboard-stand", label: "Keyboard", cat: "Music & Fitness", w: 140, h: 40, desc: "electric keyboard on stand" },
    ],
  },
  {
    file: "g08-office",
    items: [
      { id: "conference-table", label: "Conference table", cat: "Office", w: 300, h: 160, desc: "long conference table with ten chairs" },
      { id: "reception-desk", label: "Reception desk", cat: "Office", w: 200, h: 100, desc: "curved reception desk" },
      { id: "cubicle", label: "Cubicle", cat: "Office", w: 150, h: 150, desc: "office cubicle with desk and partition walls" },
      { id: "whiteboard", label: "Whiteboard", cat: "Office", w: 120, h: 40, desc: "whiteboard on rolling stand" },
      { id: "printer-stand", label: "Printer", cat: "Office", w: 60, h: 50, desc: "office printer on stand" },
      { id: "server-rack", label: "Server rack", cat: "Office", w: 60, h: 60, desc: "server rack" },
      { id: "lockers", label: "Lockers", cat: "Office", w: 120, h: 45, desc: "row of lockers" },
      { id: "water-cooler", label: "Water cooler", cat: "Office", w: 35, h: 35, desc: "water cooler" },
      { id: "photocopier", label: "Photocopier", cat: "Office", w: 70, h: 60, desc: "photocopier machine" },
      { id: "podium", label: "Podium", cat: "Office", w: 50, h: 45, desc: "speaker podium" },
      { id: "meeting-table", label: "Meeting table", cat: "Office", w: 160, h: 160, desc: "round meeting table with four chairs" },
      { id: "phone-booth", label: "Phone booth", cat: "Office", w: 100, h: 100, desc: "office phone booth pod" },
      { id: "file-shelf", label: "File shelving", cat: "Office", w: 120, h: 40, desc: "open file shelving" },
      { id: "lounge-set", label: "Lounge set", cat: "Office", w: 200, h: 100, desc: "two lounge chairs with small table" },
      { id: "double-workstation", label: "Double workstation", cat: "Office", w: 160, h: 120, desc: "double desk workstation face to face" },
      { id: "kiosk", label: "Kiosk", cat: "Office", w: 60, h: 60, desc: "information kiosk" },
    ],
  },
  {
    file: "g09-outdoor",
    items: [
      { id: "patio-set", label: "Patio set", cat: "Outdoor", w: 180, h: 180, desc: "patio table with four chairs" },
      { id: "sun-lounger", label: "Sun lounger", cat: "Outdoor", w: 60, h: 190, desc: "sun lounger" },
      { id: "hammock", label: "Hammock", cat: "Outdoor", w: 120, h: 300, desc: "hammock between two posts" },
      { id: "bbq-grill", label: "BBQ grill", cat: "Outdoor", w: 70, h: 50, desc: "barbecue grill" },
      { id: "fire-pit", label: "Fire pit", cat: "Outdoor", w: 90, h: 90, desc: "round fire pit" },
      { id: "garden-bench", label: "Garden bench", cat: "Outdoor", w: 140, h: 50, desc: "garden bench" },
      { id: "swing-set", label: "Swing set", cat: "Outdoor", w: 250, h: 150, desc: "children swing set with two swings" },
      { id: "trampoline", label: "Trampoline", cat: "Outdoor", w: 250, h: 250, desc: "round trampoline" },
      { id: "pool-rect", label: "Pool (rect)", cat: "Outdoor", w: 500, h: 300, desc: "rectangular swimming pool with ladder" },
      { id: "pool-round", label: "Pool (round)", cat: "Outdoor", w: 350, h: 350, desc: "round swimming pool" },
      { id: "hot-tub", label: "Hot tub", cat: "Outdoor", w: 200, h: 200, desc: "round hot tub with seats" },
      { id: "umbrella-table", label: "Umbrella table", cat: "Outdoor", w: 180, h: 180, desc: "table with open umbrella seen from above" },
      { id: "planter-box", label: "Planter box", cat: "Outdoor", w: 100, h: 35, desc: "rectangular planter box with plants" },
      { id: "slide", label: "Slide", cat: "Outdoor", w: 100, h: 200, desc: "playground slide" },
      { id: "sandbox", label: "Sandbox", cat: "Outdoor", w: 120, h: 120, desc: "square sandbox with toys" },
      { id: "seesaw", label: "Seesaw", cat: "Outdoor", w: 180, h: 40, desc: "seesaw" },
    ],
  },
  {
    file: "g10-garden",
    items: [
      { id: "tree-large", label: "Large tree", cat: "Garden", w: 300, h: 300, desc: "large tree canopy" },
      { id: "tree-small", label: "Small tree", cat: "Garden", w: 150, h: 150, desc: "small tree canopy" },
      { id: "bush", label: "Bush", cat: "Garden", w: 80, h: 80, desc: "round bush" },
      { id: "hedge", label: "Hedge", cat: "Garden", w: 200, h: 50, desc: "rectangular trimmed hedge" },
      { id: "flower-bed", label: "Flower bed", cat: "Garden", w: 150, h: 60, desc: "flower bed with blooms" },
      { id: "palm-plant", label: "Palm plant", cat: "Garden", w: 60, h: 60, desc: "potted palm plant" },
      { id: "cactus", label: "Cactus", cat: "Garden", w: 40, h: 40, desc: "potted cactus" },
      { id: "monstera", label: "Monstera", cat: "Garden", w: 70, h: 70, desc: "potted monstera plant" },
      { id: "fern", label: "Fern", cat: "Garden", w: 50, h: 50, desc: "potted fern" },
      { id: "bonsai", label: "Bonsai", cat: "Garden", w: 35, h: 35, desc: "bonsai tree on tray" },
      { id: "stepping-stones", label: "Stepping stones", cat: "Garden", w: 60, h: 180, desc: "row of stepping stones" },
      { id: "pond", label: "Pond", cat: "Garden", w: 250, h: 180, desc: "organic-shaped garden pond" },
      { id: "fountain", label: "Fountain", cat: "Garden", w: 150, h: 150, desc: "round tiered garden fountain" },
      { id: "boulder", label: "Boulder", cat: "Garden", w: 80, h: 60, desc: "decorative boulder" },
      { id: "vegetable-bed", label: "Vegetable bed", cat: "Garden", w: 180, h: 90, desc: "raised vegetable bed with rows" },
      { id: "greenhouse", label: "Greenhouse", cat: "Garden", w: 250, h: 180, desc: "small greenhouse structure" },
    ],
  },
  {
    file: "g11-decor",
    items: [
      { id: "rug-rect", label: "Rug", cat: "Decor", w: 200, h: 140, desc: "rectangular rug with border pattern" },
      { id: "rug-round", label: "Round rug", cat: "Decor", w: 150, h: 150, desc: "round rug" },
      { id: "rug-runner", label: "Runner rug", cat: "Decor", w: 250, h: 80, desc: "long runner rug" },
      { id: "rug-oval", label: "Oval rug", cat: "Decor", w: 180, h: 120, desc: "oval rug" },
      { id: "rug-cowhide", label: "Cowhide rug", cat: "Decor", w: 180, h: 160, desc: "cowhide-shaped rug" },
      { id: "floor-lamp", label: "Floor lamp", cat: "Decor", w: 35, h: 35, desc: "floor lamp seen from above" },
      { id: "statue", label: "Statue", cat: "Decor", w: 50, h: 50, desc: "statue on pedestal" },
      { id: "aquarium", label: "Aquarium", cat: "Decor", w: 120, h: 45, desc: "aquarium with fish" },
      { id: "floor-vase", label: "Floor vase", cat: "Decor", w: 35, h: 35, desc: "large floor vase" },
      { id: "floor-mirror", label: "Floor mirror", cat: "Decor", w: 60, h: 25, desc: "leaning floor mirror" },
      { id: "room-divider", label: "Room divider", cat: "Decor", w: 160, h: 30, desc: "zigzag folding room divider screen" },
      { id: "globe", label: "Globe", cat: "Decor", w: 40, h: 40, desc: "globe on stand" },
      { id: "telescope", label: "Telescope", cat: "Decor", w: 50, h: 50, desc: "telescope on tripod" },
      { id: "easel", label: "Easel", cat: "Decor", w: 60, h: 60, desc: "painting easel" },
      { id: "sculpture", label: "Sculpture", cat: "Decor", w: 60, h: 60, desc: "abstract sculpture" },
      { id: "grandfather-clock", label: "Grandfather clock", cat: "Decor", w: 45, h: 30, desc: "grandfather clock" },
    ],
  },
  {
    file: "g12-games",
    items: [
      { id: "pool-table", label: "Pool table", cat: "Games & Kids", w: 250, h: 140, desc: "billiard pool table with balls" },
      { id: "ping-pong", label: "Ping pong table", cat: "Games & Kids", w: 270, h: 150, desc: "ping pong table with net" },
      { id: "foosball", label: "Foosball", cat: "Games & Kids", w: 140, h: 75, desc: "foosball table" },
      { id: "arcade", label: "Arcade cabinet", cat: "Games & Kids", w: 70, h: 80, desc: "arcade game cabinet" },
      { id: "air-hockey", label: "Air hockey", cat: "Games & Kids", w: 200, h: 100, desc: "air hockey table" },
      { id: "chess-table", label: "Chess table", cat: "Games & Kids", w: 120, h: 60, desc: "chess table with two chairs" },
      { id: "play-mat", label: "Play mat", cat: "Games & Kids", w: 150, h: 150, desc: "kids play mat with road pattern" },
      { id: "high-chair", label: "High chair", cat: "Games & Kids", w: 55, h: 55, desc: "baby high chair" },
      { id: "toy-house", label: "Toy house", cat: "Games & Kids", w: 90, h: 70, desc: "kids playhouse" },
      { id: "ball-pit", label: "Ball pit", cat: "Games & Kids", w: 120, h: 120, desc: "ball pit full of balls" },
      { id: "pet-bed", label: "Pet bed", cat: "Games & Kids", w: 60, h: 60, desc: "round pet bed" },
      { id: "dog-crate", label: "Dog crate", cat: "Games & Kids", w: 90, h: 60, desc: "dog crate" },
      { id: "cat-tree", label: "Cat tree", cat: "Games & Kids", w: 60, h: 60, desc: "cat tower seen from above" },
      { id: "litter-box", label: "Litter box", cat: "Games & Kids", w: 45, h: 35, desc: "cat litter box" },
      { id: "bird-cage", label: "Bird cage", cat: "Games & Kids", w: 50, h: 50, desc: "bird cage on stand" },
      { id: "dart-board", label: "Darts area", cat: "Games & Kids", w: 60, h: 40, desc: "dartboard cabinet open" },
    ],
  },
  {
    file: "g13-indian-kitchen",
    items: [
      { id: "gas-stove-2", label: "Gas stove (2)", cat: "Indian Kitchen", w: 60, h: 40, desc: "two-burner gas stove" },
      { id: "gas-cylinder", label: "Gas cylinder", cat: "Indian Kitchen", w: 35, h: 35, desc: "LPG gas cylinder seen from above" },
      { id: "mixer-grinder", label: "Mixer grinder", cat: "Indian Kitchen", w: 30, h: 40, desc: "mixer grinder appliance" },
      { id: "wet-grinder", label: "Wet grinder", cat: "Indian Kitchen", w: 40, h: 40, desc: "tabletop wet grinder" },
      { id: "pressure-cooker", label: "Pressure cooker", cat: "Indian Kitchen", w: 35, h: 45, desc: "pressure cooker with handle" },
      { id: "kadai", label: "Kadai", cat: "Indian Kitchen", w: 40, h: 40, desc: "round kadai wok with two handles" },
      { id: "tawa", label: "Tawa", cat: "Indian Kitchen", w: 35, h: 40, desc: "flat round tawa griddle with handle" },
      { id: "idli-steamer", label: "Idli steamer", cat: "Indian Kitchen", w: 35, h: 35, desc: "round idli steamer pot" },
      { id: "matka", label: "Matka", cat: "Indian Kitchen", w: 40, h: 40, desc: "round clay water pot" },
      { id: "water-drum", label: "Water drum", cat: "Indian Kitchen", w: 50, h: 50, desc: "steel water storage drum" },
      { id: "water-purifier", label: "Water purifier", cat: "Indian Kitchen", w: 40, h: 25, desc: "RO water purifier unit" },
      { id: "tiffin", label: "Tiffin carrier", cat: "Indian Kitchen", w: 20, h: 20, desc: "stacked tiffin carrier" },
      { id: "masala-box", label: "Masala box", cat: "Indian Kitchen", w: 25, h: 25, desc: "round spice box with seven bowls open" },
      { id: "thali-stack", label: "Thali stack", cat: "Indian Kitchen", w: 30, h: 30, desc: "stack of round steel thali plates" },
      { id: "roti-basket", label: "Roti basket", cat: "Indian Kitchen", w: 25, h: 25, desc: "round roti basket" },
      { id: "indian-platform", label: "Kitchen platform", cat: "Indian Kitchen", w: 240, h: 60, desc: "long kitchen granite platform with inset sink and stove" },
    ],
  },
  {
    file: "g14-indian-living",
    items: [
      { id: "diwan", label: "Diwan", cat: "Indian Living", w: 190, h: 90, desc: "diwan daybed with bolster pillows" },
      { id: "charpai", label: "Charpai", cat: "Indian Living", w: 100, h: 190, desc: "woven rope cot charpai" },
      { id: "jhoola", label: "Jhoola swing", cat: "Indian Living", w: 150, h: 60, desc: "wooden indoor swing bench" },
      { id: "floor-seating", label: "Floor seating", cat: "Indian Living", w: 200, h: 150, desc: "floor mattress seating with bolster cushions" },
      { id: "pooja-mandir", label: "Pooja mandir", cat: "Indian Living", w: 90, h: 50, desc: "home temple pooja mandir unit" },
      { id: "sandook", label: "Sandook", cat: "Indian Living", w: 100, h: 55, desc: "carved wooden chest" },
      { id: "mudha", label: "Mudha stool", cat: "Indian Living", w: 40, h: 40, desc: "round cane mudha stool" },
      { id: "carrom-board", label: "Carrom board", cat: "Indian Living", w: 90, h: 90, desc: "carrom board with coins" },
      { id: "tv-showcase", label: "TV showcase", cat: "Indian Living", w: 180, h: 50, desc: "TV showcase wall unit" },
      { id: "antique-trunk", label: "Steel trunk", cat: "Indian Living", w: 90, h: 50, desc: "metal storage trunk" },
      { id: "floor-cushions", label: "Floor cushions", cat: "Indian Living", w: 120, h: 120, desc: "group of four square floor cushions" },
      { id: "bajot", label: "Bajot table", cat: "Indian Living", w: 60, h: 60, desc: "low square wooden bajot table" },
      { id: "chowki", label: "Chowki", cat: "Indian Living", w: 45, h: 45, desc: "small low wooden platform seat" },
      { id: "peacock-chair", label: "Peacock chair", cat: "Indian Living", w: 90, h: 90, desc: "large cane peacock chair" },
      { id: "brass-urli", label: "Brass urli", cat: "Indian Living", w: 60, h: 60, desc: "round brass urli bowl with floating flowers" },
      { id: "diwan-side", label: "Wooden sofa set", cat: "Indian Living", w: 220, h: 90, desc: "carved wooden three-seat sofa with cushions" },
    ],
  },
  {
    file: "g15-indian-bedroom",
    items: [
      { id: "steel-almirah", label: "Steel almirah", cat: "Indian Bedroom", w: 90, h: 50, desc: "steel almirah wardrobe" },
      { id: "wooden-almirah", label: "Wooden almirah", cat: "Indian Bedroom", w: 120, h: 55, desc: "double door wooden almirah" },
      { id: "box-bed", label: "Box bed", cat: "Indian Bedroom", w: 180, h: 200, desc: "box storage bed with headboard" },
      { id: "folding-cot", label: "Folding cot", cat: "Indian Bedroom", w: 75, h: 180, desc: "folding metal cot" },
      { id: "mosquito-bed", label: "Net bed", cat: "Indian Bedroom", w: 160, h: 200, desc: "bed with mosquito net corner poles" },
      { id: "dressing-table", label: "Dressing table", cat: "Indian Bedroom", w: 90, h: 45, desc: "dressing table with oval mirror and stool" },
      { id: "sewing-machine", label: "Sewing machine", cat: "Indian Bedroom", w: 90, h: 45, desc: "sewing machine with treadle table" },
      { id: "iron-board", label: "Iron table", cat: "Indian Bedroom", w: 110, h: 35, desc: "ironing board with iron" },
      { id: "clothes-stand", label: "Drying stand", cat: "Indian Bedroom", w: 150, h: 60, desc: "folding clothes drying stand with hanging clothes" },
      { id: "bucket-mug", label: "Bucket & mug", cat: "Indian Bedroom", w: 35, h: 35, desc: "bucket with mug" },
      { id: "sil-batta", label: "Sil batta", cat: "Indian Bedroom", w: 45, h: 60, desc: "flat grinding stone with roller" },
      { id: "chakki", label: "Chakki", cat: "Indian Bedroom", w: 50, h: 50, desc: "round stone flour mill" },
      { id: "inverter", label: "Inverter", cat: "Indian Bedroom", w: 45, h: 40, desc: "inverter with battery on trolley" },
      { id: "godrej-locker", label: "Locker safe", cat: "Indian Bedroom", w: 50, h: 45, desc: "small steel locker safe" },
      { id: "khatiya", label: "Khatiya", cat: "Indian Bedroom", w: 95, h: 185, desc: "traditional woven khatiya cot" },
      { id: "telephone-table", label: "Telephone table", cat: "Indian Bedroom", w: 60, h: 40, desc: "telephone table with chair" },
    ],
  },
  {
    file: "g16-indian-utility",
    items: [
      { id: "squat-toilet", label: "Indian toilet", cat: "Indian Utility", w: 55, h: 75, desc: "indian squat toilet pan" },
      { id: "geyser", label: "Geyser", cat: "Indian Utility", w: 45, h: 30, desc: "wall water heater geyser" },
      { id: "twin-tub-washer", label: "Twin-tub washer", cat: "Indian Utility", w: 75, h: 45, desc: "semi automatic twin tub washing machine" },
      { id: "hand-pump", label: "Hand pump", cat: "Indian Utility", w: 40, h: 80, desc: "hand water pump with spout" },
      { id: "well", label: "Well", cat: "Indian Utility", w: 150, h: 150, desc: "round stone well with rope pulley" },
      { id: "sintex-tank", label: "Water tank", cat: "Indian Utility", w: 120, h: 120, desc: "round plastic water storage tank" },
      { id: "bath-stool", label: "Bath patla", cat: "Indian Utility", w: 35, h: 25, desc: "low bathing stool" },
      { id: "dhobi-stone", label: "Washing stone", cat: "Indian Utility", w: 60, h: 45, desc: "slanted clothes washing stone" },
      { id: "tulsi-planter", label: "Tulsi vrindavan", cat: "Indian Utility", w: 60, h: 60, desc: "square tulsi vrindavan planter" },
      { id: "desert-cooler", label: "Desert cooler", cat: "Indian Utility", w: 60, h: 60, desc: "desert air cooler box" },
      { id: "stand-fan", label: "Pedestal fan", cat: "Indian Utility", w: 50, h: 50, desc: "pedestal fan seen from above" },
      { id: "ceiling-fan", label: "Ceiling fan", cat: "Indian Utility", w: 120, h: 120, desc: "ceiling fan with three blades seen from above" },
      { id: "table-fan", label: "Table fan", cat: "Indian Utility", w: 35, h: 35, desc: "table fan" },
      { id: "plastic-drum", label: "Plastic drum", cat: "Indian Utility", w: 45, h: 45, desc: "plastic storage drum" },
      { id: "buckets-set", label: "Buckets", cat: "Indian Utility", w: 70, h: 35, desc: "row of three buckets" },
      { id: "clothesline", label: "Clothesline", cat: "Indian Utility", w: 250, h: 30, desc: "clothesline between two poles with clothes" },
    ],
  },
  {
    file: "g17-indian-dining",
    items: [
      { id: "floor-dining", label: "Floor dining", cat: "Indian Dining", w: 200, h: 150, desc: "floor dining setup with low tables and mats" },
      { id: "dining-6-indian", label: "Dining (6)", cat: "Indian Dining", w: 200, h: 120, desc: "six seat dining table with thali place settings" },
      { id: "small-fridge", label: "Small fridge", cat: "Indian Dining", w: 55, h: 55, desc: "single door refrigerator" },
      { id: "study-table", label: "Study table", cat: "Indian Dining", w: 110, h: 60, desc: "study table with books and lamp" },
      { id: "entrance-shoe-rack", label: "Shoe cabinet", cat: "Indian Dining", w: 90, h: 35, desc: "entrance shoe cabinet with slippers" },
      { id: "umbrella-stand", label: "Umbrella stand", cat: "Indian Dining", w: 25, h: 25, desc: "umbrella stand with umbrellas" },
      { id: "showcase", label: "Showcase", cat: "Indian Dining", w: 150, h: 45, desc: "glass showcase cabinet with curios" },
      { id: "magazine-rack", label: "Magazine rack", cat: "Indian Dining", w: 40, h: 30, desc: "magazine rack" },
      { id: "murti-stand", label: "Murti pedestal", cat: "Indian Dining", w: 45, h: 45, desc: "idol pedestal stand" },
      { id: "samai", label: "Brass lamp", cat: "Indian Dining", w: 30, h: 30, desc: "tall brass oil lamp samai seen from above" },
      { id: "pooja-side-table", label: "Pooja table", cat: "Indian Dining", w: 60, h: 40, desc: "small pooja side table with bell and incense" },
      { id: "bar-unit", label: "Bar unit", cat: "Indian Dining", w: 120, h: 50, desc: "bar cabinet with bottles" },
      { id: "verandah-jhoola", label: "Verandah jhoola", cat: "Indian Dining", w: 180, h: 80, desc: "outdoor verandah swing with chains" },
      { id: "scooter", label: "Scooter", cat: "Indian Dining", w: 70, h: 180, desc: "parked scooter" },
      { id: "bicycle", label: "Bicycle", cat: "Indian Dining", w: 60, h: 180, desc: "parked bicycle" },
      { id: "motorcycle", label: "Motorcycle", cat: "Indian Dining", w: 80, h: 200, desc: "parked motorcycle" },
    ],
  },
  {
    file: "g18-indian-misc",
    items: [
      { id: "palna", label: "Palna cradle", cat: "Indian Misc", w: 60, h: 100, desc: "hanging baby cradle palna" },
      { id: "grain-bin", label: "Grain bin", cat: "Indian Misc", w: 60, h: 60, desc: "tall grain storage bin kothi" },
      { id: "pickle-jars", label: "Pickle jars", cat: "Indian Misc", w: 60, h: 30, desc: "row of ceramic pickle jars barni" },
      { id: "tandoor", label: "Tandoor", cat: "Indian Misc", w: 70, h: 70, desc: "round clay tandoor oven" },
      { id: "mud-chulha", label: "Mud chulha", cat: "Indian Misc", w: 70, h: 50, desc: "traditional mud stove chulha" },
      { id: "stone-bench", label: "Stone bench", cat: "Indian Misc", w: 150, h: 45, desc: "stone garden bench" },
      { id: "aram-kursi", label: "Aram kursi", cat: "Indian Misc", w: 70, h: 110, desc: "reclining planters easy chair with long armrests" },
      { id: "hookah", label: "Hookah", cat: "Indian Misc", w: 30, h: 30, desc: "hookah pipe" },
      { id: "thela-cart", label: "Thela cart", cat: "Indian Misc", w: 100, h: 180, desc: "wooden hand cart thela" },
      { id: "rangoli", label: "Rangoli", cat: "Indian Misc", w: 100, h: 100, desc: "circular decorative rangoli pattern" },
      { id: "dhurrie", label: "Dhurrie rug", cat: "Indian Misc", w: 180, h: 120, desc: "flat woven dhurrie rug with striped pattern" },
      { id: "jute-mat", label: "Jute mat", cat: "Indian Misc", w: 120, h: 70, desc: "rectangular jute mat" },
      { id: "bamboo-ladder", label: "Bamboo ladder", cat: "Indian Misc", w: 40, h: 200, desc: "bamboo ladder lying flat" },
      { id: "kalash-set", label: "Brass pots", cat: "Indian Misc", w: 60, h: 30, desc: "set of three brass water pots kalash" },
      { id: "swing-bench", label: "Swing bench", cat: "Indian Misc", w: 160, h: 70, desc: "garden swing bench with canopy" },
      { id: "gate-arch", label: "Entrance arch", cat: "Indian Misc", w: 150, h: 40, desc: "decorative entrance gate arch top view" },
    ],
  },
  {
    file: "g19-cozy",
    cols: 4,
    rows: 2,
    items: [
      { id: "teddy-sofa", label: "Teddy bear sofa", cat: "Seating", w: 220, h: 110, desc: "giant plush teddy bear shaped sofa, bear arms as armrests and ears at the top" },
      { id: "fort-classic", label: "Pillow fort", cat: "Pillow Forts", w: 200, h: 180, desc: "classic pillow fort of stacked sofa cushions with a blanket roof half open" },
      { id: "fort-castle", label: "Fort castle", cat: "Pillow Forts", w: 250, h: 250, desc: "pillow fort castle with four cushion corner towers and cushion walls" },
      { id: "fort-teepee", label: "Blanket teepee", cat: "Pillow Forts", w: 150, h: 150, desc: "round blanket teepee fort with poles and entrance flap" },
      { id: "fort-tunnel", label: "Fort tunnel", cat: "Pillow Forts", w: 100, h: 250, desc: "long pillow fort crawl tunnel made of arched cushions" },
      { id: "fort-sofa", label: "Sofa fort", cat: "Pillow Forts", w: 220, h: 180, desc: "fort built against a sofa using its cushions and a draped blanket" },
      { id: "fort-bed", label: "Bed fort", cat: "Pillow Forts", w: 200, h: 220, desc: "blanket fort built over a bed with string lights" },
      { id: "fort-box", label: "Box fort", cat: "Pillow Forts", w: 150, h: 150, desc: "cardboard box fort with cut-out door and a small flag" },
    ],
  },
  {
    file: "g20-special",
    cols: 1,
    rows: 1,
    items: [
      { id: "eemans-table", label: "Eeman's table (my table)", cat: "Special", w: 180, h: 100, desc: "Eeman's gloriously cluttered desk, drawn from a real photo" },
    ],
  },
];

// Programmatically drawn sprites (scripts/draw-pools.py): catalog entries only, no sheet to slice.
export const DRAWN = [
  { id: "pool-infinity", label: "Infinity pool", cat: "Outdoor", w: 480, h: 260 },
  { id: "pool-lap", label: "Lap pool", cat: "Outdoor", w: 250, h: 800 },
  { id: "pool-plunge", label: "Plunge pool", cat: "Outdoor", w: 250, h: 200 },
  { id: "pool-l", label: "Pool (L-shaped)", cat: "Outdoor", w: 500, h: 400 },
  { id: "pool-oval", label: "Pool (oval)", cat: "Outdoor", w: 450, h: 300 },
  { id: "pool-kidney", label: "Pool (kidney)", cat: "Outdoor", w: 450, h: 320 },
  { id: "kids-pool", label: "Kids' pool", cat: "Outdoor", w: 180, h: 180 },
];

// Re-generated replacement sprites: sliced like SHEETS but NOT added to the catalog
// (their ids already exist there).
export const FIX_SHEETS = [
  {
    file: "g21-vehicles",
    cols: 3,
    rows: 1,
    items: [
      { id: "bicycle" },
      { id: "scooter" },
      { id: "motorcycle" },
    ],
  },
  {
    file: "g22-fixes",
    cols: 2,
    rows: 1,
    items: [{ id: "nightstand" }, { id: "water-drum" }],
  },
];

export function sheetPrompt(sheet) {
  const cols = sheet.cols ?? 4;
  const nRows = sheet.rows ?? 4;
  const rows = Array.from({ length: nRows }, (_, r) =>
    `Row ${r + 1}: ` +
    sheet.items
      .slice(r * cols, r * cols + cols)
      .map((it, i) => `${r * cols + i + 1}) ${it.desc}`)
      .join(", ")
  );
  return (
    "Generate an image: architectural floor-plan symbols, top-down plan view (bird's eye), minimalist thin black line art, TRANSPARENT background PNG, landscape orientation. " +
    `A STRICT ${cols}x${nRows} grid of ${sheet.items.length} separate objects in equal-size cells with generous empty space between them so no two objects touch, ordered row by row EXACTLY as follows. ` +
    rows.join(". ") +
    ". Every object drawn strictly from directly above (plan view), consistent line weight. No text, no labels, no numbers, no shadows, no gray fills, no background. Pure black outlines on a transparent background only."
  );
}

// Print all prompts when run directly
if (process.argv[1] && process.argv[1].endsWith("catalog-def.mjs")) {
  for (const s of SHEETS) {
    console.log(`\n===== ${s.file} =====\n${sheetPrompt(s)}`);
  }
}
